### ISSUE TITLE
Algorithm bug in Calculate function in Processing.c

### ISSUE THREAD

**Issue by sadrasabouri** [sadrasabouri/Chortke#3]
@hhadian Hi.
We decided not to use formal algorithm to solve equation instead we've define a recursive function that use it's stack to calculate equations.
It will call itself whenever it's poped character is ')'.
and it'll ignore + and - when there is a more important operator like * or / are in the parentheses.
it's process is running upward respected to mathematics formal direction (due to stacks). 
[Processing.zip](https://github.com/sadrasabouri/Chortke/files/2682614/Processing.zip)

**Comment by hhadian** [comment]
@sadrasabouri Try to show me some line of code and ask a more specific question so I can help. E.g. a link  like this: https://github.com/sadrasabouri/Chortke/blob/master/Chortke.c#L18

**Comment by sadrasabouri** [comment]
@hhadian Thank you.
The problem has been solved.

**Comment by sadrasabouri** [comment]
Yeah you are right.
[+](https://github.com/sadrasabouri/Chortke/blob/master/Chortke.c#L17) First we push open parentheses into the character stack :  
[+](https://github.com/sadrasabouri/Chortke/blob/master/Chortke.c#L18)Then we start the inputting process that which add numbers to theirs stack and operators to theirs stack.
[+](https://github.com/sadrasabouri/Chortke/blob/master/Chortke.c#L19) Then we push close parentheses into the character stack : 

As i told our recursive algorithm will repeat until: 
[+](https://github.com/sadrasabouri/Chortke/blob/master/Chortke.c#L22) The operator stack isn't empty.


Now There is a problem [here](https://github.com/sadrasabouri/Chortke/blob/master/Lib/Processing.c#L69)
Note that we check equation after the stack has completely filled.
In this function in each step we pop a operator from the character stack if it is ')' so we [call the function again
](https://github.com/sadrasabouri/Chortke/blob/master/Lib/Processing.c#L75) if it's '(' [it'll return from function and go on calculating](https://github.com/sadrasabouri/Chortke/blob/master/Lib/Processing.c#L78).
in other cases [if the operator is * or /](https://github.com/sadrasabouri/Chortke/blob/master/Lib/Processing.c#L93) we just pop two number from stack and then push the result into the number stack but [in + or -](https://github.com/sadrasabouri/Chortke/blob/master/Lib/Processing.c#L81) cases it will pop a number, call itself, pop second one and then push the result into number stack.
Thank you. 😄

**Comment by hhadian** [comment]
The links do not work anymore. I assume you have updated/fixed the issues..
