### ISSUE TITLE
English mistakes

### ISSUE THREAD

**Issue by Thepunisher79** [sadrasabouri/Chortke#8]
Hello dude,
I can just say that your code is incredibly fantastic!
there's just one thing which may lower the quality of your work and that's some very rare mistakes in your English probably occurred while fast typing and when you were tired.by correcting that mistakes I ensure you that your code becomes perfect!
Thanks a bunch

**Comment by sadrasabouri** [comment]
@Thepunisher79 Thank you for your nice words :+1: 
Fixed
